CREATE TABLE IF NOT EXISTS clients
(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    first_name VARCHAR(40) NOT NULL,
    last_name VARCHAR(40) NOT NULL,
    middle_name VARCHAR(40),
    date_of_birth DATE NOT NULL,
    email VARCHAR(60) NOT NULL,
    phone VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS rooms
(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    title VARCHAR(40) NOT NULL,
    room_number VARCHAR(4) NOT NULL
);

CREATE TABLE IF NOT EXISTS requests
(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    client_id INT NOT NULL,
    room_id INT NOT NULL,
    reserved_from DATETIME NOT NULL,
    reserved_till DATETIME NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);